function iap = get_current_density_fast(precalculated, t, z, zi, L1, L2, v, d, suppress_endplate_density, endplate_width)
%This function modelizes the individual (IAP) or single fiber (SFAP) action
%potential in space and time coordinates, try this as an example:
%iap = get_current_density(0:1e-3:1, 0:1e-1:100, 50, 50, 50, 5000);
%figure; plot(iap(:,40));
% Taken from Farina, Merletti - A Novel Approach for Precise Simulation of the EMG Signal 
% Detected by Surface Electrodes. 2001; Principle coming from Dimitrov -
% Dimitrova 1998.
% t - vector of time
% z - vector of coordinates along the muscle fiber
% zi - position of endplate
% L1 - length of muscle fiber from zi to positive end (tendon)
% L2 - length of muscle fiber from zi to negative end (tendon)
% v - conduction speed in mm/s
% d - diameter of fiber in mm
% suppress_endplate_density (1 by default) - put to zero the density in the
% area of endplate (zi-dz : zi+dz);

% ToDo: fix the non-symmetricity of left and right waveforms. They should
% add up to zero at any time point!


if nargin < 9
    suppress_endplate_density = 1;
    endplate_width = 0.5; %mm
end

dz = mean(diff(z));
z = [z(:); z(end)+dz];

[T,Z] = meshgrid(t,z);

% As originally formulated in Farina's article:
%psi1 = -get_tm_current_dz(-(Z-zi-v*T));
%%psi2 = get_tm_current_dz(-(-Z+zi-v*T));

% Correction from Simulation of single muscle fibre action potentials by 
% S. D. Nandedkar and E. Stalberg. Real intercellular current is 4 times
% bigger and two times faster that analytical one:

tendon_terminator = @(z_inline, L_inline) z_inline <= L_inline/2 & z_inline >= -L_inline/2;

if L1 >= L2
    psi = -4*precalculated( max(1,round((-2*(Z-zi-v*T))/dz)) );
    %psi = -get_tm_current_dz(-(Z-zi-v*T));
    longest_wave = diff(psi) / dz;
    longest_wave = longest_wave .* tendon_terminator(Z(1:end-1,:)-zi-L1/2, L1);
    longest_wave = longest_wave .* ((Z(1:end-1, :) - zi)/v > 0); % Negative time suppression
else
    psi = 4*precalculated( max(1,round((-2*(-Z+zi-v*T))/dz)) );
    %psi = get_tm_current_dz(-(-Z+zi-v*T));
    longest_wave = diff(psi) / dz;
    longest_wave = longest_wave .* tendon_terminator(Z(1:end-1,:)-zi+L2/2, L2);
    longest_wave = longest_wave .* ((-Z(1:end-1, :) + zi)/v > 0);
end

%Original version, produces weird peaks at the tendon/muscle junction due
%to indicating function:
%right_wave = psi1.*tendon_terminator(Z-zi-L1/2, L1);
%left_wave = psi2.*tendon_terminator(Z-zi+L2/2, L2);
%iap = diff(right_wave - left_wave)/dz; 

% My version:

shortest_wave = longest_wave(end:-1:1, :);
shortest_wave = shift_padding(shortest_wave, round((L1 + L2 - max(z) + L2 - L1)/dz), 1);
% left_wave = left_wave .* ((-Z(1:end-1, :) + zi)/v > 0);

if L1 >= L2
    shortest_wave = shortest_wave .* tendon_terminator(Z(1:end-1,:)-zi+L2/2, L2);
    iap = longest_wave - shortest_wave; 
else
    shortest_wave = shortest_wave .* tendon_terminator(Z(1:end-1,:)-zi-L1/2, L1);
    iap = shortest_wave - longest_wave; 
end

if suppress_endplate_density
    endplate_terminator = @(z_inline) z_inline <= (zi-endplate_width) | z_inline >= (zi+endplate_width);
    iap = iap .* endplate_terminator(Z(1:end-1, :));
end

if nargin < 7
    d = 55e-6; %default value for muscle fiber diameter is 55um.
end

%%
% According to formula 8.19 given in Malmivuo and Plonsey 1995 - 
% Bioelectromagnetism. 8. Source-Field Models, potential generated by
% a distribution of current sources along fiber is given as:
% Phi_0 = sigma_i/(4pi*r(sigma_a, sigma_b)) * int(d2(Vm)/d2)dx
% This function returns, thus Phi_0 * r(sigma_a, sigma_b) for subsequent
% convolution.

sigma_i = 1.01 * 1000; % [Sn/mm] Intracellular conductivity from ANDREASSEN and ROSENFALCK (1980) 
%                       (taken from Nandedkar Stalberg - Simulation of single muscle fibre action potentials)

d = d * 1000; % Get millimeters
iap = iap * sigma_i * pi*((d/2)^2)/4; % This formula is consistent with Hamilton-Wrigth's model
                                      % Only difference, it's radius
                                      % instead of diameter.
end

